# Generated by Django 5.2.3 on 2025-07-01 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schlüsselwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, unique=True)),
                ('preis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpielerProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpielerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_key', models.CharField(max_length=20)),
                ('abgeschlossen_am', models.DateTimeField(auto_now_add=True)),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spielerprofil')),
            ],
        ),
        migrations.CreateModel(
            name='SpielerSchlüsselwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gekauft_am', models.DateTimeField(auto_now_add=True)),
                ('schlüsselwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schlüsselwort')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spielerprofil')),
            ],
        ),
    ]
