# Generated by Django 5.2.3 on 2025-06-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('mission', models.IntegerField()),
                ('punkte', models.IntegerField()),
                ('loesung', models.TextField()),
            ],
        ),
    ]
