# Generated by Django 5.2.3 on 2025-07-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spieldaten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='punkte',
            field=models.IntegerField(default=0),
        ),
    ]
